// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>Responsive</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Responsive.Controllers {

    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;

    public partial class urlset {
        
        private List<System.Xml.XmlElement> anyField;
        
        private List<tUrl> urlField;
        
        public urlset() {
            this.urlField = new List<tUrl>();
            this.anyField = new List<System.Xml.XmlElement>();
        }
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlElement> Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        public List<tUrl> url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    public partial class tUrl {
        
        private string locField;
        
        private string lastmodField;
        
        private tChangeFreq changefreqField;
        
        private bool changefreqFieldSpecified;
        
        private decimal priorityField;
        
        private bool priorityFieldSpecified;
        
        private List<System.Xml.XmlElement> anyField;
        
        public tUrl() {
            this.anyField = new List<System.Xml.XmlElement>();
        }
        
        public string loc {
            get {
                return this.locField;
            }
            set {
                this.locField = value;
            }
        }
        
        public string lastmod {
            get {
                return this.lastmodField;
            }
            set {
                this.lastmodField = value;
            }
        }
        
        public tChangeFreq changefreq {
            get {
                return this.changefreqField;
            }
            set {
                this.changefreqField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changefreqSpecified {
            get {
                return this.changefreqFieldSpecified;
            }
            set {
                this.changefreqFieldSpecified = value;
            }
        }
        
        public decimal priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlElement> Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    public enum tChangeFreq {
        
        /// <remarks/>
        always,
        
        /// <remarks/>
        hourly,
        
        /// <remarks/>
        daily,
        
        /// <remarks/>
        weekly,
        
        /// <remarks/>
        monthly,
        
        /// <remarks/>
        yearly,
        
        /// <remarks/>
        never,
    }
}
