//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Responsive.Controllers {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;

    public partial class urlset {
        
        private List<System.Xml.XmlElement> anyField;
        
        private List<tUrl> urlField;
        
        public urlset() {
            this.urlField = new List<tUrl>();
            this.anyField = new List<System.Xml.XmlElement>();
        }
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlElement> Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("url")]
        public List<tUrl> url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sitemaps.org/schemas/sitemap/0.9")]
    public partial class tUrl {
        
        private string locField;
        
        private string lastmodField;
        
        private tChangeFreq changefreqField;
        
        private bool changefreqFieldSpecified;
        
        private decimal priorityField;
        
        private bool priorityFieldSpecified;
        
        private List<System.Xml.XmlElement> anyField;
        
		public tUrl() {
            this.anyField = new List<System.Xml.XmlElement>();
        }
		
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string loc {
            get {
                return this.locField;
            }
            set {
                this.locField = value;
            }
        }
        
        public string lastmod {
            get {
                return this.lastmodField;
            }
            set {
                this.lastmodField = value;
            }
        }
        
        public tChangeFreq changefreq {
            get {
                return this.changefreqField;
            }
            set {
                this.changefreqField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changefreqSpecified {
            get {
                return this.changefreqFieldSpecified;
            }
            set {
                this.changefreqFieldSpecified = value;
            }
        }
        
        public decimal priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlElement> Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sitemaps.org/schemas/sitemap/0.9")]
    public enum tChangeFreq {
        
        /// <remarks/>
        always,
        
        /// <remarks/>
        hourly,
        
        /// <remarks/>
        daily,
        
        /// <remarks/>
        weekly,
        
        /// <remarks/>
        monthly,
        
        /// <remarks/>
        yearly,
        
        /// <remarks/>
        never,
    }
}
