//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Responsive.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResponsiveContext : DbContext
    {
        public ResponsiveContext()
            : base("name=ResponsiveContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Article_Content> Article_Content { get; set; }
        public virtual DbSet<Navigation> Navigation { get; set; }
        public virtual DbSet<Navigation_ChangeLogs> Navigation_ChangeLogs { get; set; }
        public virtual DbSet<Navigation_PublishLogs> Navigation_PublishLogs { get; set; }
        public virtual DbSet<Article_ChangeLogs> Article_ChangeLogs { get; set; }
        public virtual DbSet<Article_PublishLogs> Article_PublishLogs { get; set; }
        public virtual DbSet<Article_Metadata> Article_Metadata { get; set; }
        public virtual DbSet<Navigation_Content> Navigation_Content { get; set; }
    }
}
